### ISSUE TITLE
Bbox issue

### ISSUE THREAD

**Issue by barshathakuri** [IFRCGo/alert-hub-web-app#126] opened 2024-05-22 10:24 UTC
could you please still review the various b-boxes? We still need to manually adjust the b-box data for countries that have over seas territories so that it goes to the main land, for example France and possibly the Netherlands. it seems to be fine for the UK.

**Comment by thenav56** [comment] 2024-05-27 15:28
Duplicate of https://github.com/IFRCGo/alert-hub-backend/issues/50

**Closed as completed by thenav56** 2024-05-27 15:28 UTC
